### ISSUE TITLE
Hive  default database fails to pass the verification

### ISSUE THREAD

**Issue by ASimpleCoder** [ExpediaGroup/waggle-dance#260]
**Describe the bug**
when I start the waggle-dance, I have the following problem.

**To Reproduce**
Here is my federation configuration.

primary-meta-store:
  access-control-type: READ_ONLY
  database-prefix: ''
  ...
federated-meta-stores:
- access-control-type: READ_ONLY
  database-name-mapping: {}
  database-prefix: xf
  ...
  writable-database-white-list: []

**Expected behavior**
I expected waggle-dance will start successfully, but it not success, The following is the log information.
The “default” is the default hive database. My two hive metadatastore services contain the default database, What should I do?

**Logs**
Caused by: com.hotels.bdp.waggledance.api.WaggleDanceException: Database clash, found 'default' to be mapped for the federated metastore 'xf' already present in the primary database, please remove the database from the list it can't be accessed via Waggle Dance

**Versions (please complete the following information):**
 - Waggle Dance Version: 3.10.10
 - Hive Versions: 3.1.3

**Additional context**
Is there anyone who can help me? Thank you very much.

**Comment by ASimpleCoder** [comment]
Is there anyone who can help me? Thank you very much.

**Comment by javsanbel2** [comment]
Hey sorry for the late reply, in case of database clashing you have two options:
- You can add a prefix to one of your federations so all the dbs appear like prefix_default
- You can filter out the default database if you don't need it
