### ISSUE TITLE
how to disable spring actuator

### ISSUE THREAD

**Issue by zzzzming95** [ExpediaGroup/waggle-dance#263]
I see Waggle-dance support `spring actuator` by defalut. I would like to disable it (close the socket 18000) . 

I can set `management.endpoints.enabled-by-default=false` to make all `Endpoint` disable , but the socket 18000 also keep listen. And i try to remove `spring-boot-starter-actuator` dependency from pom.xml , but it not work .

Can anyone tell me how to close this port? Thanks~

gentel ping ~ @javsanbel2

**Comment by javsanbel2** [comment]
Hey @zzzzming95 , could you tell me in which package you put the application properties file for setting `management.endpoints.enabled-by-default=false` property?

**Comment by javsanbel2** [comment]
Which is the reason you would like to disable the port? Is there any conflict? Maybe you could try to switch the actuator port to other number?
