### ISSUE TITLE
Add configuration to enable exposing all monitoring data through Prometheus"

### ISSUE THREAD

**Issue by cs-lpc** [ExpediaGroup/waggle-dance#290]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example - I'm always frustrated when [...]

In our scenario, we only have Prometheus-related services for viewing monitoring data. Therefore, we migrated all monitoring data from Waggledance to Prometheus. But currently, Waggledance cannot switch from Graphite to Prometheus through configuration. Therefore, I want to implement this feature.

**Describe the solution you'd like**

Get prometheusMeterRegistry if needed in MonitoredAspect. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by DhrubajyotiSadhu** [comment]
WaggleDance exposes metrics to Prometheus too : 

Link: https://github.com/ExpediaGroup/waggle-dance/blob/774f6700091b1716101a9bda7a795c5d0e474c86/waggle-dance-core/pom.xml#L111

You will be able to find the metrics if you run 
curl -v localhost:18000/prometheus/actuator

Kindly let me know if you need anything else

**Comment by cs-lpc** [comment]
Yes, I just tested it and found that after the first request, request metrics are also exposed to Prometheus. However, I noticed that these metrics do not include p75 and p90, which exist in metastore. Can I implement them?

**Comment by patduin** [comment]
Would it be possible to do this on Prometheus side https://prometheus.io/docs/practices/histograms/
We'll be more flexible that way if someone want a different percentile.
