### ISSUE TITLE
Support Audit Log For waggle-dance

### ISSUE THREAD

**Issue by jueshali** [ExpediaGroup/waggle-dance#324]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add audit log for waggle dance

**Describe alternatives you've considered**
By hook

**Additional context**

**Comment by jmnunezizu** [comment]
Hi @jueshali – please include additional information about your issue. If it's a feature request, you should include:

1. How do you see it working?
2. Why do you need this feature?

Thanks.

**Comment by jueshali** [comment]
How do you see it working?
This function can audit user access requests on the server side. Record client IP, UGI, etc.

Why do you need this feature?
This function can help me locate some abnormal business requests, such as delete drop and other unusual  user request, replace metastore's audit feature

**Comment by jmnunezizu** [comment]
@jueshali – have you considered using Ranger (https://cwiki.apache.org/confluence/display/RANGER/Ranger+Plugin+for+Hive+MetaStore)?

**Comment by jueshali** [comment]
Ranger can auditing  authentication behaviors, but we also want to record the number of partitions returned and whether there are behaviors such as scanning the entire table. This will help us locate anomalous jobs.

**Comment by jueshali** [comment]
```
2024-07-10 09:33:16,686 INFO HiveMetaStore.audit: ugi=xxx    ip=xx.xx.xx.95 cmd=get_table size=     
```
this is example for hive meta audit log

**Comment by jueshali** [comment]
@jmnunezizu  hello，This is important for us, I will implement this feature in our internal version. Can you give me some code development advice? tks

**Comment by patduin** [comment]
We added this this not so long ago does that help: https://github.com/ExpediaGroup/waggle-dance/tree/main/waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/server#L57

**Comment by jueshali** [comment]
very outstanding work thks

**Comment by patduin** [comment]
I'll close this then.
